name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        qt-version: '6' # Specify the version of Qt you want to use

    - name: Set up environment variables
      run: |
        echo "CMAKE_PREFIX_PATH=$RUNNER_WORKSPACE/Qt/6/windows_x86_64" >> $GITHUB_ENV           

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2.2.0
      with:
        platform: x64
        version: 12.2.0

    - name: package
      run: bash build.sh --package-msi

    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows Installer
        path: latest-alpha_windows.zip