name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_windows:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: package
      bash build.sh --package-linux
        
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: GNU Linux Archive
        path: embroidermodder_2.0.0-alpha_linux.tar