name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2.2.0
      with:
        platform: x64
        version: 12.2.0 

    - name: package
      run: |
        curl https://raw.githubusercontent.com/Inrixia/Embroidermodder/main/build.sh > build.sh
        bash build.sh --package-msi

    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows Installer
        path: latest-alpha_windows.zip
