name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_windows:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: package
      run: bash build.sh --package-msi

    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows Installer
        path: latest-alpha_windows.zip